name: Build Gatsby and deploy to Netlify

on:
  repository_dispatch:
    types: [update_post]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm i
      - run: npm ci
      - run: npm run build
      - uses: netlify/actions/cli@master
        env:
          apiKey: ${{secrets.GATSBY_MICRO_CMS_API_KEY}}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public --prod
          secrets: '["GATSBY_MICRO_CMS_API_KEY","NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
